apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  {{- if .Values.configMap.env }}
  {{- range $key, $value := .Values.configMap.env }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
