apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.prometheus }}
      annotations:
        prometheus.io/path: {{ .Values.prometheus.path }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
      {{- else }}
      annotations:
        {{ toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.irsa }}
      serviceAccountName: {{ required ".Values.irsa.name is required" .Values.irsa.name }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.deployment.env }}
          env:
            {{ toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe: {{ toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe }}
          readinessProbe: {{ toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.securityContext }}
          securityContext: {{ toYaml .Values.deployment.securityContext | nindent 12 }}
          {{- end }}
