{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if  .Values.service.http }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    {{- end }}
    {{- if  .Values.service.https }}
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
