name: "Deploy Application"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        required: true
        default: '[production|infrastructure]'
      dockerImage:
        description: 'Docker Tag to Deploy'
        required: true
        default: 'latest'


env:
  AWS_DEFAULT_REGION: us-west-2
  KUBECONFIG: ${{ github.workspace }}/infrastructure/.kube/config

jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install aws-iam-authenticator
        run: brew install aws-iam-authenticator
      - name: Assume necessary role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORLANDOWEST_PRODUCTION_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.ORLANDOWEST_PRODUCTION_AWS_SECRET }}
          aws-region: us-west-2
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
      - name: Deploy HELMFILE
        run: |
          cd kubernetes/clusters/ironwolf-us-west-2 && \
          kubectl config use-context aws-ironwolf-us-west-2 && \
          helmfile --file helmfile.yaml \
            --environment ${{ github.event.inputs.environment }} \
            --state-values-set dockerTag="${{ github.event.inputs.dockerImage }}" sync
